config/routes.rb
Rails.application.routes.draw do
  root :to => 'shops#index'
  get "/shops/:id/photo" => "shops#photo"
  post "/shops/:id/photo" => "shops#addphoto"
  get "/shops/junapoint" => "shops#junapoint"
  get "/shops/:id/junapoint" => "shops#editjunapoint"
  post "shops/:id/junapoint" => "shops#updatejunapoint"
  resources :shops

end

app/models/shop.rb
class Shop < ActiveRecord::Base
    attr_accessor :photo
    mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
    @shop = Shop.new
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      # flash[:success] = 'ユーザー情報を編集しました。'
      redirect_to shops_url
    else
      # flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :new
    end
  end
  
  # add photo spage
  # def photo
  #   @shop = Shop.find(params[:id])
  # end
  
  # def addphoto
  #   @shop = Shop.find(params[:id])
  #   @shop.photo = "#{@shop.id}.jpg"
  #   photo = params[:photo]
  #   File.binwrite("public/shop_images/#{@shop.photo}", photo.read)
  #   @shop.save
  #   redirect_to "/shops"
  # end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      # flash[:success] = 'ユーザー情報を編集しました。'
      redirect_to shops_url
    else
      # flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def junapoint
    @shops = Shop.all
  end
  
  def editjunapoint
    @shop = Shop.find(params[:id])
  end
  
  def updatejunapoint
    @shop = Shop.find(params[:id])
    @shop.junapoint = params[:junapoint]
    @shop.save
    redirect_to "/shops/junapoint"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:contributer, :photo, :name, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>日Aランチ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
  <link rel="shortcut icon" href="favicon.ico">
  <meta property="og:image" content="https://sunday-a-lunch-2018.herokuapp.com/OGP.jpg">
</head>
<body>
<%= yield %>

</body>
</html>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="container-fluid">
  <%= form_tag("/shops", method: :post) do %>
    <div class="form-group">
        <label class="col-md-2 control-label" for="InputMentor">メンター名</label>
        <div class="col-md-10">
            <select name="mentor" id="InputMentor" class="form-control">
                <option>ベンチャー</option>
                <option>ぶっちー</option>
                <option>サカナクション</option>
                <option>みこ</option>
                <option>せぇ</option>
                <option>ちょむ</option>
                <option>かすぴー</option>
                <option>バナナ</option>
                <option>スペック</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label" for="InputName">店名</label>
        <div class="col-md-10">
            <input type="text" name="name" value="<%= @shop.name %>" id="InputName" class="form-control" required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label" for="InputComment">グルメコメント</label>
        <div class="col-md-10">
          <textarea name="comment" id="InputComment" class="form-control" required><%= @shop.comment %></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="追加" class="btn btn-success">
        </div>
    </div>
  <% end %>
</div>

app/views/shops/edit.html.erb
<div class="jumbotron">
    <h1 class="wf-sawarabigothic text-center">Editing Shop</h1>
</div>

<div class="container-fluid">
    <div class="col-12 offset-xl-1 col-xl-10">
        <%= form_for(@shop) do |f| %>
            <% if @shop.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>
                    
                    <ul>
                        <% @shop.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="form-group">
                <div class="field col-xl-3">
                    <%= f.label :contributer, "投稿者" %>
                    <%= f.text_field :contributer, class: "form-control", required: true %>
                </div>
            </div>
            <div class="text-center">
                 <% if @shop.photo? %>
                    <p><%= image_tag @shop.photo_url, :class => "col-6 col-xl-3" %></p>
                <% else %>
                    <p><%= image_tag "/images/default.jpg", :class => "col-6 col-xl-3" %></p>
                <% end %>
            </div>
            <div class="form-group">
                <div class="field">
                    <%= f.label :photo, "写真（なしでもOK）", class: "control-label" %>
                    <%= f.file_field :photo, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="field">
                    <%= f.label :name, "名前" %>
                    <%= f.text_field :name, class: "form-control", required: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="field">
                    <%= f.label :comment, "グルメコメント" %>
                    <%= f.text_area :comment, class: "form-control", required: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="actions">
                    <%= f.submit '更新', class: 'btn btn-info col-4 col-xl-1' %>
                    <%= link_to '戻る', shops_path, class: "btn btn-danger col-4 col-xl-1" %>
                </div>
            </div>
        <% end %>
    </div>
</div>
        

<!--<div class="container-fluid">-->
<!--    <div class="offset-md-1 col-md-10">-->
<!--        <%= form_tag("/shops/#{@shop.id}", method: :patch) do %>-->
<!--            <div class="form-group">-->
<!--                <label class="control-label" for="InputContributer">投稿者</label>-->
<!--                <div class="col-md-3">-->
<!--                    <input type="text" name="contributer" value="<%= @shop.contributer %>" id="InputContributer" class="form-control" required>-->
<!--                </div>-->
<!--            </div>-->
            <!--<div class="form-group">-->
            <!--    <label class="control-label" for="InputMentor">メンター名</label>-->
            <!--    <div class="col-md-3">-->
            <!--        <select name="mentor" id="InputMentor" class="form-control">-->
            <!--            <option></option>-->
            <!--            <option>ベンチャー</option>-->
            <!--            <option>ぶっちー</option>-->
            <!--            <option>サカナクション</option>-->
            <!--            <option>みこ</option>-->
            <!--            <option>せぇ</option>-->
            <!--            <option>ちょむ</option>-->
            <!--            <option>かすぴー</option>-->
            <!--            <option>バナナ</option>-->
            <!--            <option>スペック</option>-->
            <!--        </select>-->
            <!--    </div>-->
            <!--</div>-->
<!--            <div class="form-group">-->
<!--                <label class="control-label" for="InputName">店名</label>-->
<!--                <input type="text" name="name" value="<%= @shop.name %>" id="InputName" class="form-control" required>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <label class="control-label" for="InputComment">グルメコメント</label>-->
<!--                <textarea name="comment" id="InputComment" class="form-control" required><%= @shop.comment %></textarea>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="submit" value="次へ" class="btn btn-info col-md-1">-->
<!--                <%= link_to '戻る', shops_path, class: "btn btn-danger col-md-1" %>-->
<!--            </div>-->
<!--        <% end %>-->
<!--    </div>-->
<!--</div>-->

app/views/shops/editjunapoint.html.erb
<div class="jumbotron">
    <h1 class="wf-sawarabigothic text-center">ゅなさん専用ページ</h1>
</div>
<%= form_tag("/shops/#{@shop.id}/junapoint", method: :post) do %>
    <div class="form-group">
        <label class="control-label" for="InputJunapoint">ゅなポイントは</label>
        <div class="col-md-3">
            <input type="text" name="junapoint" value="<%= @shop.junapoint %>" id="InputJunapoint" class="form-control" required>
        </div>
        <label>点</label>
    </div>
    <div class="form-group">
        <input type="submit" value="完了" class="btn btn-info col-md-1">
        <%= link_to '戻る', "/shops/junapoint", class: "btn btn-danger col-md-1" %>
    </div>
<% end %>

app/views/shops/index.html.erb
<div class="jumbotron">
  <h1 class="wf-sawarabigothic text-center">日Aランチ</h1>
</div>

<div class="text-center">
  <p>
    <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1a06CRCYRQt9hM8hqurrxHvQHw6U37r5x" width="900" height="480"></iframe>
  </p>
  <h6>マップの更新はちょっと時間がかかるでぃ</h6>
</div>

<div class="container-fluid">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3>行った店リスト</h3>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width:5%">NO.</th>
              <th style="width:10%">投稿者</th>
              <th style="width:10%">写真</th>
              <th style="width:10%">店名</th>
              <th>グルメコメント</th>
              <th style="width:5%"></th>
              <th style="width:5%"></th>
              <th style="width:12%">ゅなポイント</th>
            </tr>
          </thead>
          <tbody>
            <% @shops.each_with_index do |shop, i| %>
              <tr>
                <td><%= i+1 %></td>
                <td><%= shop.contributer %></td>
                <% if shop.photo? %>
                  <td><%= image_tag shop.photo_url, :style => "width:100%" %></td>
                <% else %>
                  <td><%= image_tag "/images/default.jpg", :style => "width:100%" %></td>
                <% end %>
                <td><%= shop.name %></td>
                <td><%= shop.comment %></td>
                <td><%= link_to '編集', edit_shop_path(shop), class: "btn btn-info" %></td>
                <td><%= link_to '削除', shop, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
                <% if shop.junapoint != nil %>
                  <td><%= shop.junapoint %></td>
                <% else %>
                  <td>判定中</td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="text-center mt-3">
      <p><button class="shopAddButton btn btn-success">店の追加</button></p>
      <div id="shopAddForm">
        <div class="offset-xl-2 col-xl-8">
          <%= form_for(@shop) do |f| %>
              <% if @shop.errors.any? %>
                  <div id="error_explanation">
                      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>
                      <ul>
                          <% @shop.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                          <% end %>
                      </ul>
                  </div>
              <% end %>
              <div class="form-group">
                  <div class="field offset-3 col-6 offset-xl-4 col-xl-4">
                      <%= f.label :contributer, "投稿者" %>
                      <%= f.text_field :contributer, class: "form-control", required: true %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="field">
                      <%= f.label :photo, "写真（なしでもOK）", class: "control-label" %>
                      <%= f.file_field :photo, class: "form-control" %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="field">
                      <%= f.label :name, "名前" %>
                      <%= f.text_field :name, class: "form-control", required: true %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="field">
                      <%= f.label :comment, "グルメコメント" %>
                      <%= f.text_area :comment, class: "form-control", required: true %>
                  </div>
              </div>
              <div class="form-group">
                  <div class="actions">
                      <%= f.submit '追加', class: 'btn btn-info col-4 col-xl-1' %>
                      <button class="shopAddButton btn btn-danger col-4 col-xl-1">戻る</button>
                  </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/junapoint.html.erb
<div class="jumbotron">
    <h1 class="wf-sawarabigothic text-center">ゅなさん専用ページ</h1>
</div>
<div class="container-fluid">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3>行った店リスト</h3>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width:5%">NO.</th>
              <th style="width:10%">投稿者</th>
              <th style="width:10%">写真</th>
              <th style="width:10%">店名</th>
              <th>グルメコメント</th>
              <th style="width:5%"></th>
              <th style="width:5%"></th>
              <th style="width:12%">ゅなポイント</th>
            </tr>
          </thead>
        
          <tbody>
            <% @shops.each_with_index do |shop, i| %>
              <tr>
                <td><%= i+1 %></td>
                <td><%= shop.contributer %></td>
                <td><img alt="" src="<%= "/shop_images/#{shop.photo}" %>" style="width:100%"></td>
                <td><%= shop.name %></td>
                <td><%= shop.comment %></td>
                <td></td>
                <td></td>
                <% if shop.junapoint != nil %>
                  <td><%= shop.junapoint %>
                <% else %>
                  <td>判定中
                <% end %>
                <%= link_to '編集', "/shops/#{shop.id}/junapoint", class: "btn btn-success" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="text-center">
  <p><%= link_to '戻る', new_shop_path, class: "btn btn-info" %></p>
</div>

app/views/shops/new.html.erb
<div class="jumbotron">
    <h1 class="wf-sawarabigothic text-center">New Shop</h1>
</div>

<div class="container-fluid">
    <div class="col-12 offset-xl-1 col-xl-10">
        <%= form_for(@shop) do |f| %>
            <% if @shop.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>
                    <ul>
                        <% @shop.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="form-group">
                <div class="field col-6 col-xl-3">
                    <%= f.label :contributer, "投稿者" %>
                    <%= f.text_field :contributer, class: "form-control", required: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="field">
                    <%= f.label :photo, "写真（なしでもOK）", class: "control-label" %>
                    <%= f.file_field :photo, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="field">
                    <%= f.label :name, "名前" %>
                    <%= f.text_field :name, class: "form-control", required: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="field">
                    <%= f.label :comment, "グルメコメント" %>
                    <%= f.text_area :comment, class: "form-control", required: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="actions">
                    <%= f.submit '追加', class: 'btn btn-info col-4 col-xl-1' %>
                    <%= link_to '戻る', shops_path, class: "btn btn-danger col-4 col-xl-1" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<!--<div class="container-fluid">-->
<!--    <div class="offset-md-1 col-md-10">-->
<!--        <%= form_tag("/shops", method: :post) do %>-->
<!--            <div class="form-group">-->
<!--                <label class="control-label" for="InputContributer">投稿者</label>-->
<!--                <div class="col-md-3">-->
<!--                    <input type="text" name="contributer" id="InputContributer" class="form-control" required>-->
<!--                </div>-->
<!--            </div>-->
            <!--<div class="form-group">-->
            <!--    <label class="control-label" for="InputMentor">メンター名</label>-->
            <!--    <div class="col-md-3">-->
            <!--        <select name="mentor" id="InputMentor" class="form-control">-->
            <!--            <option></option>-->
            <!--            <option>ベンチャー</option>-->
            <!--            <option>ぶっちー</option>-->
            <!--            <option>サカナクション</option>-->
            <!--            <option>みこ</option>-->
            <!--            <option>せぇ</option>-->
            <!--            <option>ちょむ</option>-->
            <!--            <option>かすぴー</option>-->
            <!--            <option>バナナ</option>-->
            <!--            <option>スペック</option>-->
            <!--        </select>-->
            <!--    </div>-->
            <!--</div>-->
<!--            <div class="form-group">-->
<!--                <label class="control-label" for="InputName">店名</label>-->
<!--                <div>-->
<!--                    <input type="text" name="name" value="<%= @shop.name %>" id="InputName" class="form-control" required>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <label class="control-label" for="InputComment">グルメコメント</label>-->
<!--                <div>-->
<!--                  <textarea name="comment" id="InputComment" class="form-control" required><%= @shop.comment %></textarea>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="submit" value="次へ" class="btn btn-info col-md-1">-->
<!--                <%= link_to '戻る', shops_path, class: "btn btn-danger col-md-1" %>-->
<!--            </div>-->
<!--        <% end %>-->
<!--    </div>-->
<!--</div>-->

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mentor:</strong>
  <%= @shop.mentor %>
</p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @shop.comment %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>